apiVersion: apps/v1
kind: Deployment
metadata:
  name: feitufi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feitufi
  template:
    metadata:
      labels:
        app: feitufi
    spec:
      containers:
      - image: okteto.dev/feitufi:latest
        name: feitufi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "80a14450-f712-4681-b859-a07f46b86ea5"
        - name: Vless_Path
          value: "/vl6759"
        - name: Vmess_UUID
          value: "80a14450-f712-4681-b859-a07f46b86ea5"
        - name: Vmess_Path
          value: "/vm8e7r"
        - name: Share_Path
          value: "/v2link"
